### ISSUE TITLE
[Bug report]: Eventlistener bug

### ISSUE THREAD

**Issue by UmarAli6** [scania-digital-design-system/tegel#115]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/tegel/issues) reported.
- [X] I have checked the latest version if the bug exist there. See all available packages at [npmJS.com](https://www.npmjs.com/package/@scania/tegel)
- [X] I have followed the installation guide.

### Package versions

@scania/tegel 0.0.8

### Browser

Edge (Chromium)

### Framework

Angular

### Version

Angular 15

### Reproduction steps

Added the sdds-toggle component in the html. Tried adding an eventlistener in the .ts ngOnInit(). Got a compile time error "property does not exist on type 'Event" on the event.**detail**.toggleid and on event.**detail**.checked. Property detail.

### Code example

      const toggleElement = document.querySelector("sdds-toggle");

      toggleElement.addEventListener("sddsToggle", (event) => {
        console.log("Toggle with id: ", event.detail.toggleId, " is ", event.detail.checked);
      });

### Screenshots

Add/Copy screenshot here

### Expected behaviour

detail should be recognized.

### Console errors

error TS2339: Property 'detail' does not exist on type 'Event'.

143         console.log("Toggle with id: ", event.detail.toggleId, " is ", event.detail.checked);

### Contact information

umar.ali@scania.com

**Comment by mJarsater** [comment]
Hi!

This is due to us emitting a custom event, were all the data we append to the event is on the detail object. It wont cause any issues in runtime, it's just that typescript wont believe it since it thinks 'event' in this case is if type Event. I would recommend typing the event as any for now and wait for future releases to get full typesafety.

` toggleElement.addEventListener("sddsToggle", (event: any) => {
    console.log("Toggle with id: ", event.detail.toggleId, " is ", event.detail.checked);
  });`

Will close this issue for now.
