### ISSUE TITLE
[Bug report]: Table header arrows pointing in the wrong direction 

### ISSUE THREAD

**Issue by jolalab** [scania-digital-design-system/tegel#596]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/tegel/issues) reported.
- [X] I have checked the latest version if the bug exist there. See all available packages at [npmJS.com](https://www.npmjs.com/package/@scania/tegel)
- [X] I have followed the installation guide.

### Package versions

@scania/tegel-angular: 1.8.0

### Browser

Chrome

### Framework

Angular

### Version

Angular 17

### Reproduction steps

There are 2 bugs
- Add a tds table with sortable header
- Add a console log that captures the emitted event when you click to sort by column header
- Bug no 1: All arrows pointing down on hover (even though I have not sorted any column).
- Bug no 2: When the event emits "desc", the arrow ends up pointing upwards. When event emits "asc" the arrow ends up pointing downwards.

### Code example

Reproducible on official Tegel Storybook page

### Expected behaviour

1. When you have not sorted on any column header, there should be double opposite arrows (pointing up and down) on all columns on hover. 
Actual initial state: All arrows pointing down on hover.

2. When event emits "desc" the arrow should end up pointing downwards. When event emits "asc" the arrow should end up pointing upwards.
Actual sorted state: When event emits "desc" the arrow ends up pointing upwards. When event emits "asc" the arrow ends up pointing downwards. 

### Console errors

Add warning/error message

### Contact information

jonatan.lampa@scania.com

**Comment by Wadzabi** [comment]
Hello everyone. I created a pull request for solving the same thing last year #449 only difference being upwards arrow instead of double arrow on initial hover to make it clear what sorting direction is set when clicking. During the review it was mentioned that we wanted to introduce more features regarding the sorting but I did not end up finding time for it and the request was later closed due to inactivity.

 If we are fine with going ahead with only changing the arrow direction for now and not adding the extra features mentioned in the pull request I could reopen the pull request.

**Comment by theJohnnyMe** [comment]
Released in version 1.12.0.
