### ISSUE TITLE
[Bug report]: When changing the slider input field value the tdsChange event should be triggered

### ISSUE THREAD

**Issue by patrikhultgren** [scania-digital-design-system/tegel#744]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/tegel/issues) reported.
- [X] I have checked the latest version if the bug exist there. See all available packages at [npmJS.com](https://www.npmjs.com/package/@scania/tegel)
- [X] I have followed the installation guide.

### Package versions

@scania/tegel: 1.13.0

### Browser

Chrome

### Framework

React

### Version

React 18.3.1

### Reproduction steps

1. Go to https://tds-storybook.tegel.scania.com/?path=/story/components-slider--default&args=showInput:true
2. Look at the console.
3. Change the value in the input field.
4. No tdsChange event is logged until the user blurs the field.

### Expected behaviour

The tdsChange event should be triggered even before blur. Because what if the user never blurs the field, and for example presses some "Save"-button directly. Then the consuming app won't have to correct value in state.

### Contact information

patrik.hultgren@scania.com

**Comment by Lunkan89** [comment]
Hi @patrikhultgren I will close this one for now since you should be able to use `tdsInput` event for monitoring every value change.
https://tegel.scania.com/components/slider/code
or notes tab in storybook:
https://tds-storybook.tegel.scania.com/?path=/info/components-slider--default

If there is any issues in the future feel free to open a new issue :)
